services:
  web:
    build: ./web
    ports:
      - '3000:3000'
  server:
    build: ./server
    ports:
      - '8080:8080'
    environment:
      TMDB_API_KEY: ${TMDB_API_KEY}
      NOTION_API_KEY: ${NOTION_API_KEY}
      MOVIE_DB_ID: ${MOVIE_DB_ID}
      WATCH_DB_ID: ${WATCH_DB_ID}
