services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      TMDB_API_KEY: ${TMDB_API_KEY}
      NOTION_API_KEY: ${NOTION_API_KEY}
      NOTION_DB_ID: ${NOTION_DB_ID}
